version: "3"
services:
  strapi:
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: localhost   # Must match the service name below
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: SgcCsOcfQA2tPqxUBWUJ0YR8086MJHnz4RZYfMUfPLRkJVPd558BryptTUUpU1YI
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: production
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./public/uploads:/app/public/uploads
    ports:
      - "1337:1337"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SgcCsOcfQA2tPqxUBWUJ0YR8086MJHnz4RZYfMUfPLRkJVPd558BryptTUUpU1YI
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  
      
volumes:
  postgres-data:
  strapi-data:
